version: '3.8'


x-DbLoggin:
  environment:
    &db-login
    SQLURL: "jdbc:postgresql://${POSTGRES_IP}:5432/${POSGRESS_USERNAME}"
    POSGRESS_USER: "${POSGRESS_USERNAME}"
    POSTGRES_DB: "${POSGRESS_DB_NAME}"
    POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"


services:
  postgres_db:
    image: postgres

    environment:
      << :  *db-login
#      PGDATA: "/var/lib/postgresql/data/pgdata"


    volumes:
#      - type: volume
#        source: db_data
#        target: /var/lib/postgresql/data
      - type: bind
        source: ./docker_files/posgress/db_init_scripts
        target: /docker-entrypoint-initdb.d

    networks:
      internal:
        ipv4_address: "${POSTGRES_IP}"

#    ports:
#      - "5432:5432"

    restart: unless-stopped



  web_server:

    build:
      context: ./web/api
      dockerfile: ./Dockerfile

    environment:
      <<: *db-login

    volumes:
      - type: volume
        source: fractal_thumbnail_images
        target: /fractal_thumbnail_images
      - type: bind
        source: $PWD/web/api/
        target: /usr/src/app


    networks:
      internal:
        ipv4_address: "${WEBSERVER_IP}"


#    ports:
#      - "80:80"
#      - "48:48"

#    depends_on:
#      - postgres_db

    restart: unless-stopped

  server:
    container_name: docker_manager

    build:
      context: ./server
      dockerfile: Dockerfile


    environment:
      <<: *db-login


    volumes:
      - type: volume
        source: fractal_thumbnail_images
        target: /fractal_thumbnail_images


    networks:
      internal:
      frontend:

    depends_on:
      - postgres_db

    restart: unless-stopped



  # https://github.com/mikael2/payara-postgres-nginx/
#  nginx:
#    container_name: nginx
#
#    build:
#      context: ./DockerFiles/nginx_certbot
#      dockerfile: Dockerfile
#
#    volumes:
#      - type: volume
#        source: nginx_data
#        target: /etc/letsencrypt
#
#    env_file:
#      - ./config_files/nginx_cerbot.env
#
#    environment:
#      DOMAIN: "${API_DOMAIN}"
#      LE_EMAIL: "${MAIL_USERNAME}"
#    logging:
#      options:
#        max-size: "50m"
#        max-file: "3"
#
#    ports:
#      - "80:80"
#      - "443:443"
#
#    networks:
#      frontend:
#      internal:
#
#    depends_on:
#      - api_server
#
#    restart: unless-stopped


networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/8


  frontend:

volumes:
  # posgres db
  db_data:

  # thumbnail images
  fractal_thumbnail_images:

  nginx_data:
